# Generated by Django 5.1.1 on 2024-12-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_assignment_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='code_zip_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_zips/'),
        ),
    ]
