# Generated by Django 5.1.1 on 2024-12-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_assignment_options_assignment_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='class_name',
            field=models.CharField(default='Default Class', max_length=100),
        ),
    ]
