# Generated by Django 5.1.1 on 2024-12-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_assignment_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submitted_pdf',
            field=models.FileField(blank=True, null=True, upload_to='submitted_pdfs/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submitted_zip',
            field=models.FileField(blank=True, null=True, upload_to='submitted_zips/'),
        ),
    ]
